// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Key: typeof import('./src/components/key.vue')['default']
    KeyGroup: typeof import('./src/components/key-group.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/components/switch.vue')['default']
  }
}
